### ISSUE TITLE
6v6 bug in Overtime

### ISSUE THREAD

**Issue by abdulsami34** [splewis/csgo-pug-setup#277] opened 2019-03-23 02:05 UTC
Hello there, 
I have been experiencing this bug for last few weeks i guess. I kinda ignored it. So what happens, Whenever the match goes to Over Time, who ever connects to the server automatically joins a team 6v5, So we have to force him to go to spectate or kick him. This happens only in Overtime. I have teamlocker plugin enable as well. The match goes fine without overtime no problems. This happens only in OT. Any idea?

- Plugin version: 2.0.5 (Aug 6 ,2018)
- Sourcemod version: 1.9 - build 6275

I have tried using older sourcemod build as well.

**Comment by splewis** [comment] 2019-04-01 01:40
The teamlocker plugin probably doesn't work. I don't suggest relying on it (it's more likely to be deleted from pugsetup than fixed). Otherwise seems like a duplicate of #236, although in overtime only.

**Closed by splewis** 2019-04-01 01:40 UTC
Labels: duplicate
