### ISSUE TITLE
Map Picking

### ISSUE THREAD

**Issue by Twistedwheelbarrow** [splewis/csgo-pug-setup#99] opened 2015-09-28 15:01 UTC
First, I just want to say great job as I have been using this for a while. The problem is that if you use the captain veto system for the maps and use it in conjunction with the captains pick teams, it makes you pick maps before teams.

I think it'd be a little better if it worked the opposite way around in this case. For example, once teams have been picked they then veto maps one by one so they can choose a map that fits their team!

Just a suggestion :3

**Comment by splewis** [comment] 2015-09-28 16:30
It would make more sense, but has the same problems as I put here: https://github.com/splewis/csgo-pug-setup/issues/92

Storing teams across mapchanges is non-trivial. Perhaps I could try storing the teams in a steamid->team mapping so a player disconnecting & reconnecting doesn't break it, though.

**Comment by Twistedwheelbarrow** [comment] 2015-09-28 18:36
Could you not use similar authentication to that of sourcemod when you decide to authenticate Steam admins using their ID? I mean, I don't personally create plugins, but I'd imagine you would need to temporarily store the IDs of both teams in a database which is cleared when the game is finished or has been forced to end?

Either way, we work around it but it'd be a great addition to an already great plugin.

**Comment by splewis** [comment] 2015-09-28 18:39
Yes, that's roughly what would be added. It just time consuming to test and is very bug prone.

**Comment by splewis** [comment] 2016-09-10 18:21
Closing since it's a duplicate of https://github.com/splewis/csgo-pug-setup/issues/92

**Closed by splewis** 2016-09-10 18:21 UTC
