### ISSUE TITLE
30 sec. Pause Timer [FEATURE REQUEST]

### ISSUE THREAD

**Issue by CXZichan** [splewis/csgo-pug-setup#371] opened 2021-03-02 09:47 UTC
I liked to have on my Prac / Scrim Server a Feature, that allows me to make the pauses in Scrims 30 sec. long with 4 times on each Site and not infinite like it is now.

I tried some Codes from the Get5 Plugin (I know it is not working because it is a another Plugin) and I tried these Commands but without any sucess
"
mp_team_timeout_time 30
mp_team_timeout_max 4
"

**Comment by splewis** [comment] 2022-07-05 22:31
Closing as a duplicate of #366.


In general, I'd suggest using get5 directly for a scrim server.

**Closed by splewis** 2022-07-05 22:31 UTC
Labels: duplicate
