### ISSUE TITLE
csgo client freezes with -panorama

### ISSUE THREAD

**Issue by Justus-Jonas** [splewis/csgo-pug-setup#224] opened 2018-07-14 17:24 UTC
Dear all,

I installed the latest sourcemod and latest plugin version. 

If I start the game with panorama disabled setting up an pug is no problem.

But if I start it with panorama enabled, I can still open the pug setup with '.setup' but if I click on '1. finish setup' the complete game freezes and I am not able to tab out or close csgo --> force shut down. 
If somebody trys to join the server after finishing the setup with panorama enabled, they are getting frezzed in the loading screen and have also to force shut down they pc. 

I tried it with several machines now on different locations and the problem remains. The server keeps running and has no problems with it at all.

I hope you can help me somehow thanks in advance

and kind regards 

Justus 

### Steps to reproduce
- Plugin version: pugsetup_2.0.4
- Sourcemod version: sourcemod-1.9.0-git6245
- Steps to reproduce (please be specific):

**Comment by splewis** [comment] 2018-07-15 00:10
Closing as a duplicate of https://github.com/splewis/csgo-pug-setup/issues/226.

**Closed by splewis** 2018-07-15 00:10 UTC
