### ISSUE TITLE
Instant runoff vote

### ISSUE THREAD

**Issue by Siniiitchibo** [splewis/csgo-pug-setup#392] opened 2021-12-13 23:03 UTC
Instant runoff vote working but still with 1 bug... After all players have entered their 3 preferences. Hit message "Vote over... {1} won!" was showed for 1 sec. and after that the countdown continues as well as after map change.

**Comment by splewis** [comment] 2022-07-05 22:28
Can you reproduce this behavior and post the plugin version? I can't reproduce this. 

There supposed to be a [builtin 10-second delay](https://github.com/splewis/csgo-pug-setup/blob/507c5ed750be0c00ef4ec2b007d92ea256434133/scripting/pugsetup/instantrunoffvote.sp#L251-L253) there.

**Comment by Siniiitchibo** [comment] 2022-07-05 22:38
It was last version 2.0.7 I can make a video if u want, will be better i think

**Comment by Siniiitchibo** [comment] 2022-07-05 23:04
look at the hint message, countdown timer still working as well as after map change

[](https://youtu.be/zpiPzClWKec)

**Comment by splewis** [comment] 2022-07-05 23:06
Have you checked for any error logs under `addons/sourcemod/logs`?

**Comment by Siniiitchibo** [comment] 2022-07-05 23:10
without error message.

**Comment by splewis** [comment] 2022-07-05 23:17
I believe I see the issue; this can happen if *all* players finish voting before the timeout. The fix is in the latest build @ https://ci.splewis.net/job/csgo-pug-setup/lastBuild/ if you want to try it. (you just need the updated `addons/sourcemod/plugins/pugsetup.smx` file)

**Comment by Siniiitchibo** [comment] 2022-07-05 23:22
yeah it`s perfect...thx so much bro ;)

**Closed** 2022-12-21 02:35 UTC
Labels: unverified-bug
