### ISSUE TITLE
Help with .setup for Pug Setup and Practice Mode

### ISSUE THREAD

**Issue by chronicleCS** [splewis/csgo-pug-setup#146] opened 2016-08-03 18:51 UTC
This isn't an issue but I need help with installing both pug setup and practice mode, when I install both to my dathost server I type .setup and only practice mode works? How do I make it so they're both in the same menu?

**Comment by splewis** [comment] 2016-08-04 02:38
You don't have to do anything. You do, however, have to make sure both are relatively recently updated.

If you type ``sm plugins`` into console it will tell you the versions of each plugin. Pugsetup needs to be at least 2.0.0 to work with any practicemode binary from the last ~year.

**Comment by chronicleCS** [comment] 2016-08-04 20:03
I've got both latest versions installed, when I type .setup it only works for pug setup there is no start practice mode or anything :/

**Comment by splewis** [comment] 2016-08-05 05:56
A "launch practice mode" option appears (usually) on the 2nd page of the .setup menu. You can check the logs (``addons/sourcemod/logs``) to see if there are any error log files. And "latest" isn't a helpful version number - can you give exact versions?

**Comment by chronicleCS** [comment] 2016-08-06 17:42
There is no error log files, and on the 2nd page of the .setup menu there is nothing to be seen of "launch practice mode". I have practice mode 1.1.0 and pug setup 2.0.1.

**Comment by splewis** [comment] 2017-01-29 05:20
Closing since I was unable to reproduce. Feel free to reopen if you still think there is a bug and want to follow up.

**Closed by splewis** 2017-01-29 05:20 UTC
