### ISSUE TITLE
Pug Order

### ISSUE THREAD

**Issue by AngelGuard** [splewis/csgo-pug-setup#142] opened 2016-05-02 05:45 UTC
Hey - why have you changed the order so map vote is first then captains? 

Also I tried the .rand feature but it didn't seem to work, did I do it too early?

**Comment by splewis** [comment] 2016-05-02 06:01
I haven't changed anything about the order. There's an open issue to change it, though: https://github.com/splewis/csgo-pug-setup/issues/92

When did you use .rand?

**Comment by AngelGuard** [comment] 2016-05-03 05:04
when i first received this i used to do this..
.setup go through those settings, then .rand and it would assign cap's there and then. .

Regarding the order. Okay. Perhaps I've forgotten as its been many months

**Comment by SirBarclay** [comment] 2016-05-03 08:18
Don't know what the exact problem is.

I went into the setup. Selected captains, map vote, etc.

Then in the .ready stage I did .rand, followed by readying up.

Popped up saying I was team captain, then once everyone was ready the map voting stage began.

Is that the desired outcome or am I getting it backwards?

**Comment by splewis** [comment] 2016-09-10 18:21
Closing since it's a duplicate of https://github.com/splewis/csgo-pug-setup/issues/92

**Closed by splewis** 2016-09-10 18:21 UTC
